version: "3.7"

services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      CLIENT_ID: "jXp8_HKTov2Q1t3ev8FKYw"
      CLIENT_SECRET: "dJ-uzuKXcumSVnftexmkS0HBLaDozQ"
      BOT_TOKEN: "6491093673:AAHYFjlfJ5eR83S5SVGLTv4oIaY29c3bIus"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7-alpine
